site_name: giga-inframapkit
nav:
  - Home: index.md
  - Proximity: proximity.md
  - Coverage: coverage.md
  - Demand: demand.md
  - Fiber path: fiberpath.md
  - Visibility: visibility.md
  - Cost model: costmodel.md
theme: readthedocs