site_name: Connectivity Planning Platform Developer Documentation
nav:
  - Home: index.md
  - Model Integration Framework: integrations.md
  - Input data: inputdata.md
  - Proximity: proximity.md
  - Coverage: coverage.md
  - Demand: demand.md
  - Fiber Path: fiberpath.md
  - Visibility: visibility.md
  - Cost: costmodel.md
  - Technology Assignment: assignment.md
theme: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js